spring:
  security:
    oauth2:
      authorizationserver:
        client:
          client-1:
            require-authorization-consent: true
            registration:
              client-id: client
              client-secret: "$2a$10$Oi0rPhwffyuY85j7jsjJkekSRak5yRu2JpaCq4bVEYBR1znKLF3AK" #secret
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8082/login/oauth2/code/spring
              scopes:
                - user.read
                - user.write
                - openid
